version: '3.7'
services:
  php:
    image: php:7-apache
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
    command:
     "bash -c 'docker-php-ext-install mysqli && docker-php-ext-enable mysqli && docker-php-ext-install pdo pdo_mysql && apachectl restart && tail -f /dev/null'"  

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=joel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=joel
      - MYSQL_PASSWORD=pass
    expose:
      - 3306
    ports:
      - 3306:3306
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8082:81
    links:
      - mysql:joel
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root
    